apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-processor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: transaction-processor
  template:
    metadata:
      labels:
        app: transaction-processor
    spec:
      containers:
      - name: transaction-processor
        image: your-dockerhub-username/transaction-processor:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
