version: '3.8'
services:
  fintech:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - kafka
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
  kafka:
    image: "bitnami/kafka:latest"
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
