apiVersion: v1
kind: Service
metadata:
  name: transaction-service
spec:
  selector:
    app: transaction-processor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
